config/routes.rb
Rails.application.routes.draw do
  resources :bitacoras
  resources :voluntarios
  resources :registros
  resources :registers

   root :to => "bienvenida#index"

end

app/models/register.rb
class Register < ActiveRecord::Base
end

app/controllers/registers_controller.rb
class RegistersController < ApplicationController
  before_action :set_register, only: [:show, :edit, :update, :destroy]

  # GET /registers
  # GET /registers.json
  def index
    @registers = Register.all
  end

  # GET /registers/1
  # GET /registers/1.json
  def show
  end

  # GET /registers/new
  def new
    @register = Register.new
  end

  # GET /registers/1/edit
  def edit
  end

  # POST /registers
  # POST /registers.json
  def create
    @register = Register.new(register_params)

    respond_to do |format|
      if @register.save
        format.html { redirect_to @register, notice: 'Register was successfully created.' }
        format.json { render :show, status: :created, location: @register }
      else
        format.html { render :new }
        format.json { render json: @register.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registers/1
  # PATCH/PUT /registers/1.json
  def update
    respond_to do |format|
      if @register.update(register_params)
        format.html { redirect_to @register, notice: 'Register was successfully updated.' }
        format.json { render :show, status: :ok, location: @register }
      else
        format.html { render :edit }
        format.json { render json: @register.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registers/1
  # DELETE /registers/1.json
  def destroy
    @register.destroy
    respond_to do |format|
      format.html { redirect_to registers_url, notice: 'Register was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_register
      @register = Register.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def register_params
      params.require(:register).permit(:numero, :nombregrupo, :estado, :municipio, :localidad, :colonia, :status)
    end
end

app/helpers/registers_helper.rb
module RegistersHelper
end

app/views/registers/_form.html.erb
<%= form_for(@register) do |f| %>
  <% if @register.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@register.errors.count, "error") %> prohibited this register from being saved:</h2>

      <ul>
      <% @register.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :numero %><br>
    <%= f.number_field :numero %>
  </div>
  <div class="field">
    <%= f.label :nombregrupo %><br>
    <%= f.text_field :nombregrupo %>
  </div>
  <div class="field">
    <%= f.label :estado %><br>
    <%= f.text_field :estado %>
  </div>
  <div class="field">
    <%= f.label :municipio %><br>
    <%= f.text_field :municipio %>
  </div>
  <div class="field">
    <%= f.label :localidad %><br>
    <%= f.text_field :localidad %>
  </div>
  <div class="field">
    <%= f.label :colonia %><br>
    <%= f.text_field :colonia %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/registers/edit.html.erb
<h1>Editing Register</h1>

<%= render 'form' %>

<%= link_to 'Show', @register %> |
<%= link_to 'Back', registers_path %>

app/views/registers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Registers</h1>

<table>
  <thead>
    <tr>
      <th>Numero</th>
      <th>Nombregrupo</th>
      <th>Estado</th>
      <th>Municipio</th>
      <th>Localidad</th>
      <th>Colonia</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @registers.each do |register| %>
      <tr>
        <td><%= register.numero %></td>
        <td><%= register.nombregrupo %></td>
        <td><%= register.estado %></td>
        <td><%= register.municipio %></td>
        <td><%= register.localidad %></td>
        <td><%= register.colonia %></td>
        <td><%= register.status %></td>
        <td><%= link_to 'Show', register %></td>
        <td><%= link_to 'Edit', edit_register_path(register) %></td>
        <td><%= link_to 'Destroy', register, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Register', new_register_path %>

app/views/registers/new.html.erb
<h1>New Register</h1>

<%= render 'form' %>

<%= link_to 'Back', registers_path %>

app/views/registers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Numero:</strong>
  <%= @register.numero %>
</p>

<p>
  <strong>Nombregrupo:</strong>
  <%= @register.nombregrupo %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @register.estado %>
</p>

<p>
  <strong>Municipio:</strong>
  <%= @register.municipio %>
</p>

<p>
  <strong>Localidad:</strong>
  <%= @register.localidad %>
</p>

<p>
  <strong>Colonia:</strong>
  <%= @register.colonia %>
</p>

<p>
  <strong>Status:</strong>
  <%= @register.status %>
</p>

<%= link_to 'Edit', edit_register_path(@register) %> |
<%= link_to 'Back', registers_path %>