config/routes.rb
Rails.application.routes.draw do
  resources :bitacoras
  resources :voluntarios
  resources :registros
  resources :registers

   root :to => "bienvenida#index"

end

app/models/voluntario.rb
class Voluntario < ActiveRecord::Base

mount_uploader :attachment, AttachmentUploader

end

app/controllers/voluntarios_controller.rb
class VoluntariosController < ApplicationController
  before_action :set_voluntario, only: [:show, :edit, :update, :destroy]

  # GET /voluntarios
  # GET /voluntarios.json
  def index
    @search = Voluntario.search(params[:q])
    @voluntarios = @search.result.paginate(:page => params[:page], per_page: 10)

  
  end


  # GET /voluntarios/1
  # GET /voluntarios/1.json
  def show
  end

  # GET /voluntarios/new
  def new
    @voluntario = Voluntario.new
  end

  # GET /voluntarios/1/edit
  def edit
  end

  # POST /voluntarios
  # POST /voluntarios.json
  def create
    @voluntario = Voluntario.new(voluntario_params)

    respond_to do |format|
      if @voluntario.save
        UserMailer.registration_confirmation(@voluntario).deliver
        format.html { redirect_to @voluntario, notice: 'Voluntario was successfully created.' }
        format.json { render :show, status: :created, location: @voluntario }
      else
        format.html { render :new }
        format.json { render json: @voluntario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /voluntarios/1
  # PATCH/PUT /voluntarios/1.json
  def update
    respond_to do |format|
      if @voluntario.update(voluntario_params)
        format.html { redirect_to @voluntario, notice: 'Voluntario was successfully updated.' }
        format.json { render :show, status: :ok, location: @voluntario }
      else
        format.html { render :edit }
        format.json { render json: @voluntario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /voluntarios/1
  # DELETE /voluntarios/1.json
  def destroy
    @voluntario.destroy
    respond_to do |format|
      format.html { redirect_to voluntarios_url, notice: 'Voluntario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_voluntario
      @voluntario = Voluntario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def voluntario_params
      params.require(:voluntario).permit(:contacto, :fecha_solicitud, :fecha_autorizacion, :numero_registro, :nombre, :apellido, :estado, :municipio, :localidad, :colonia, :correo_electronico, :telefono, :status, :attachment, :comentarios, :validacionincentivos, :fecha_registro, :programa, :aportacion_cmt, :aportacion_beneficiario, :asesor)
    end
end

app/helpers/voluntarios_helper.rb
module VoluntariosHelper
end

app/views/voluntarios/edit.html.erb
<div class="container">
<div class="row">
<div class="col-lg-12">
<h2>Editar Solicitud</h2>

<%= render 'form' %>
<div class="col-xs-4 col-xs-offset-2">
<%= link_to 'Show', @voluntario, class: 'btn btn-primary' %> 
<%= link_to 'Back', voluntarios_path, class: 'btn btn-primary' %>
</div>
</div>
</div>
</div>

app/views/voluntarios/index.html.erb
 

<%= search_form_for(@search, :html => {class: "", role: "form"}) do |f| %>

  <div class="container">
   <h4><p id="notice"><%= notice %></p></h4>

  <h2>Buscar Beneficiario</h2>
 <div class="row">
<div class="col-lg-3">

<div class="form-group">
  <%= f.label :contacto_cont, "Tipo de Contacto" %>       
  <%= f.select :contacto_cont, [["Promotor voluntario", "Promotor voluntario"], ["Enlace", "Enlace"]], { :prompt => "Elegir" }, { class: "form-control" } %>
  </div>
</div>

<div class="col-lg-3">
  
<div class="form-group">
  <%= f.label :nombre_cont, "Nombre" %>
   <%= f.text_field :nombre_cont, class: "form-control", placeholder: "Nombre", autofocus: true %>
  </div>
</div>
<div class="col-lg-3">

  <div class="form-group">
    <%= f.label :apellido_cont, "Apellido" %>
   <%= f.text_field :apellido_cont, class: "form-control", placeholder: "Apellido", autofocus: true %>  
  </div>

</div>
<div class="col-lg-3">
 
<div class="form-group">
  
    <%= f.label :estado_cont, "Estado" %>
    
    <%= f.select :estado_cont, [["Aguascalientes", "Aguascalientes"], ["Baja California", "Baja California"], ["Baja California Sur", "Baja California Sur"], ["Campeche", "Campeche"], ["Chiapas", "Chiapas"], ["Chihuahua", "Chihuahua"], ["Coahuila", "Coahuila"], ["Colima", "Colima"], ["Ciudad de México", "Ciudad de México"], ["Durango", "Durango"], ["Estado de México", "Estado de México"], ["Guanajuato", "Guanajuato"], ["Guerrero", "Guerrero"], ["Hidalgo", "Hidalgo"], ["Jalisco", "Jalisco"], ["Michoacán", "Michoacán"], ["Morelos", "Morelos"], ["Nayarit", "Nayarit"], ["Nuevo León", "Nuevo León"], ["Oaxaca", "Oaxaca"], ["Puebla", "Puebla"], ["Querétaro", "Querétaro"], ["Quintana Roo", "Quintana Roo"], ["San Luis Potosí", "San Luis Potosí"], ["Sinaloa", "Sinaloa"], ["Sonora", "Sonora"], ["Tabasco", "Tabasco"], ["Tamaulipas", "Tamaulipas"], ["Tlaxcala", "Tlaxcala"], ["Veracruz", "Veracruz"], ["Yucatán", "Yucatán"], ["Zacatecas", "Zacatecas"]], {:prompt => "Elegir"}, { class: "form-control" } %>
   
  </div>

</div>

  </div>



 <div class="row">
<div class="col-lg-3">
<%= f.label :municipio_cont, "Municipio" %>
    
 <%= f.text_field :municipio_cont, class: "form-control", placeholder: "Municipio", autofocus: true %>

</div>

<div class="col-lg-3">

<div class="form-group">
 
    <%= f.label :correo_electronico_cont, "Email" %>
   
    <%= f.text_field :correo_electronico_cont, class: "form-control", placeholder: "Email", autofocus: true %>
    </div>

</div>
<div class="col-lg-3">

  <div class="form-group">
 
    <%= f.label :telefono_cont, "Teléfono" %>
    
    <%= f.number_field :telefono_cont, class: "form-control", placeholder: "Teléfono", autofocus: true %>
   
  </div>

</div>
<div class="col-lg-3">
 
 <div class="form-group">
  
      <%= f.label :status_cont, "Estatus" %>
    
    <%= f.select :status_cont, [["Inactivo", "Inactivo"], ["Aprobado", "Aprobado"]], { :prompt => "Elegir" }, { class: "form-control" } %>
    </div>

</div>
</div>


<div class="row">

<div class="col-lg-3">
    <%= f.label :fecha_solicitud_cont, "Fecha de Solicitud" %>
   </br>
    <%= f.date_select :fecha_solicitud_cont, {:prompt => { :day => 'Día', :month => 'Mes', :year => 'Año' }}, {:class => 'form-control date-select',}  %>
</div>


<div class="col-lg-3">
<div class="form-group">
      <%= f.label :fecha_autorizacion_cont, "Fecha de autorización" %></br>
    
    <%= f.date_select :fecha_solicitud, {:prompt => { :day => 'Día', :month => 'Mes', :year => 'Año' }}, {:class => 'form-control date-select'}  %>
    
  </div>

</div>
<div class="col-lg-3">
<div class="form-group">
<%= f.label :colonia_cont, "Institución" %>
<%= f.text_field :colonia_cont, class: "form-control", placeholder: "Institución", autofocus: true %>
</div>
</div>
  </div>
<div class="row">
  <div class="form-group">
  <div class=" col-lg-1">

  <%= f.submit class: 'btn btn-primary btn-lg' %></div>
 
  <div class="col-lg-1">
    <%= f.submit "Reset", :type => "reset", class: 'btn btn-primary btn-lg' %>
  </div>
   </div>
</div>
  

  
<% end %>

</div></div>
<div class="container-fluid">
   <div class="row">
      <div class="col-lg-4 text-left">
        <%= link_to 'Agregar', new_voluntario_path, :class => "btn btn-primary btn_agregar" %>
      </div>
      <div class="col-lg-8 text-right">
        <%= will_paginate @voluntarios, renderer: BootstrapPagination::Rails %> 
     

    </div>
   <div class="col-lg-12  custyle">
    <table class="table table-striped custab">

  <thead>
    <tr>
    <th><%= sort_link(@search, :contacto, "Tipo de contacto") %></th>
    
    <th><%= sort_link(@search, :nombre, "Nombre") %></th>
    <th><%= sort_link(@search, :apellido, "Apellido") %></th>
    <th><%= sort_link(@search, :fecha_Registro, "Fecha de registro") %></th>
    <th><%= sort_link(@search, :fecha_solicitud, "Fecha de solicitud") %></th>
    <th><%= sort_link(@search, :fecha_autorizacion, "Fecha de autorización") %></th>
    <th><%= sort_link(@search, :correo_electronico, "Email") %></th> 
    <th><%= sort_link(@search, :telefono, "Teléfono") %></th>
    <th><%= sort_link(@search, :colonia, "Institución") %></th>
    <th><%= sort_link(@search, :programa, "Programa") %></th>
    <th><%= sort_link(@search, :aportacion_cmt, "Aportacion Cmt") %></th>
    <th><%= sort_link(@search, :aportacion_beneficiario, "Aportacion beneficiaio") %></th>
    <th><%= sort_link(@search, :validacionincentivos, "Validacion incentivos") %></th>
    <th><%= sort_link(@search, :estado, "Estado") %></th>
    <th><%= sort_link(@search, :municipio, "Municipio") %></th>
    <th><%= sort_link(@search, :localidad, "Localidad") %></th>
    <th><%= sort_link(@search, :status, "Status") %></th>
    <th><%= sort_link(@search, :attachment, "Archivo") %></th>

    
    <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @voluntarios.each do |voluntario| %>
      <tr>
        <td><%= voluntario.contacto %></td>
    
        <td class="capitalize"><%= voluntario.nombre %></td>
        <td class="capitalize"><%= voluntario.apellido %></td>
         <td><%= voluntario.fecha_registro %></td>
        <td><%= voluntario.fecha_solicitud %></td>
        <td><%= voluntario.fecha_autorizacion %></td>       
        <td><%= voluntario.correo_electronico %></td>
        <td><%= voluntario.telefono %></td>
        <td  class="capitalize"><%= voluntario.colonia %></td>
        <td><%= voluntario.programa %></td>
        <td><%= voluntario.aportacion_cmt %></td>
        <td><%= voluntario.aportacion_beneficiario %></td>
        <td><%= voluntario.validacionincentivos %></td>
        <td><%= voluntario.estado %></td>
        <td><%= voluntario.municipio %></td>
        <td class="capitalize"><%= voluntario.localidad %></td>
       
        
        <td><%= voluntario.status %></td>
        <td><%= link_to "", voluntario.attachment_url, class:" glyphicon glyphicon-file", :target => "_blank" if voluntario.attachment? %></td>
        
        <td><%= link_to '', voluntario, class:"glyphicon glyphicon-search" %></td>
        <td><%= link_to  edit_voluntario_path(voluntario), class:"glyphicon glyphicon-edit" do  %>
        
        
        <% end %>
        </td>
        <td><%= link_to '', voluntario, class:"glyphicon glyphicon-remove", method: :delete, data: { confirm: 'Confirmar' } %></td>
      </tr>
    <% end %>
  </tbody>

</table>




</div>
 
</div>
</div>
</div>

app/views/voluntarios/new.html.erb
<div class="container">
<div class="row">
<div class="col-md-12">
<h2>Crear Solicitud</h2>

<%= render 'form' %>
<div class="col-xs-4 col-xs-offset-2">
<%= link_to 'Back', voluntarios_path, class: 'btn btn-primary'  %>
</div>
</div>
</div>
</div>

app/views/voluntarios/show.html.erb
<div class="container">
<div class="row">
<div class="col-lg-12">
<h2><b>Beneficiario:</b><span class="capitalize"><%= @voluntario.nombre %> <%= @voluntario.apellido %></span></h2>
</div>
<div class="col-lg-12">
<%= link_to 'Editar', edit_voluntario_path(@voluntario), class: 'btn btn-primary' %> 
<%= link_to 'Atras', voluntarios_path, class: 'btn btn-primary'%>
</div>
<div class="col-lg-7  custyle">
    <table class="table table-striped custab">
<thead> 
<tr>
  <th >Campos</th>
  <th >Información</th>
</tr>
</thead>

    <tbody>
    <tr>
        <th class="thshow">Contacto:</th>
        <td class="tdshow"><%= @voluntario.contacto %></td>
    </tr> 
       <tr>
        <th class="thshow">Nombre:</th>
        <td class="tdshow capitalize"><%= @voluntario.nombre %></td>

    </tr>
    <tr>
        <th class="thshow">Apellido:</th>
        <td class="tdshow capitalize"><%= @voluntario.apellido %></td>
    </tr>
    <tr>
        <th class="thshow">Numero registro:</th>
        <td class="tdshow"> <%= @voluntario.numero_registro %></td>
    </tr>
    <tr>  
         <th class="thshow"> Fecha Registro</th>
         <td class="tdshow"><%= @voluntario.fecha_registro%></td>
    </tr>
    <tr>  
         <th class="thshow"> Fecha solicitud</th>
         <td class="tdshow"><%= @voluntario.fecha_solicitud%></td>
    </tr>
    <tr>  
          <th class="thshow">Fecha autorizacion:</th>
          <td class="tdshow"><%= @voluntario.fecha_autorizacion%></td>
    </tr>
    <tr>  
          <th class="thshow">Estado</th>
          <td class="tdshow"><%= @voluntario.estado %></td>
    </tr>
    <tr>  
          <th class="thshow">Municipio</th>
          <td class="tdshow"><%= @voluntario.municipio %></td>
    </tr>
    <tr>  
          <th class="thshow">Localidad:</th>
          <td class="tdshow capitalize"><%= @voluntario.localidad %></td>
    </tr>
    <tr>  
          <th class="thshow">Institución</th>
          <td class="tdshow capitalize"> <%= @voluntario.colonia %></td>
    </tr>
    <tr>  
          <th class="thshow">Correo electronico:</th>
          <td class="tdshow"><%= @voluntario.correo_electronico %></td>
    </tr>
    <tr>  
          <th class="thshow"> Telefono: </th>
          <td class="tdshow"><%= @voluntario.telefono %></td>
    </tr>

    <tr>  
          <th class="thshow"> Programa: </th>
          <td class="tdshow"><%= @voluntario.programa %></td>
    </tr>
    <tr>  
          <th class="thshow"> Asesor: </th>
          <td class="tdshow"><%= @voluntario.asesor %></td>
    </tr>
    <tr>  
          <th class="thshow">Aportación CMT: </th>
          <td class="tdshow"><%= @voluntario.aportacion_cmt %>  </td>
    </tr>
    <tr>  
          <th class="thshow">Aportación beneficiario: </th>
          <td class="tdshow"><%= @voluntario.aportacion_beneficiario %>  </td>
    </tr>
       
    <tr>  
          <th class="thshow">Suma de aportaciones: </th>
          <td class="tdshow"><%= @voluntario.aportacion_beneficiario + @voluntario.aportacion_cmt  if @voluntario.aportacion_beneficiario? & @voluntario.aportacion_cmt?  %></td>
    </tr>

    <tr>  
          <th class="thshow">Validacion incentivos: </th>
          <td class="tdshow"><%= @voluntario.validacionincentivos %>  </td>
    </tr>
    <tr>  
          <th class="thshow">Status: </th>
          <td class="tdshow"><%= @voluntario.status %>  </td>
    </tr>
    <tr>  
          <th class="thshow">Attachment: </th>
          <td class="tdshow"><%= link_to "", @voluntario.attachment_url, :target => "_blank", class:" glyphicon glyphicon-file"  if @voluntario.attachment?%>  </td>
    </tr>
    <tr>  
          <th class="thshow">Comentarios:  </th>
          <td class="tdshow capitalize"><%= @voluntario.comentarios %>  </td>
    </tr>
       </tbody>
    </table>
</div>












</div>

</div>