config/routes.rb
Rails.application.routes.draw do
  resources :bitacoras
  resources :voluntarios
  resources :registros
  resources :registers

   root :to => "bienvenida#index"

end

app/models/bitacora.rb
class Bitacora < ActiveRecord::Base
end

app/controllers/bitacoras_controller.rb
class BitacorasController < ApplicationController
  before_action :set_bitacora, only: [:show, :edit, :update, :destroy]

  # GET /bitacoras
  # GET /bitacoras.json
  def index
     @search = Bitacora.search(params[:q])
    @bitacoras = @search.result.paginate(:page => params[:page], per_page: 10)
  end

  # GET /bitacoras/1
  # GET /bitacoras/1.json
  def show
  end

  # GET /bitacoras/new
  def new
    @bitacora = Bitacora.new
  end

  # GET /bitacoras/1/edit
  def edit
  end

  # POST /bitacoras
  # POST /bitacoras.json
  def create
    @bitacora = Bitacora.new(bitacora_params)

    respond_to do |format|
      if @bitacora.save
        format.html { redirect_to @bitacora, notice: 'Bitacora was successfully created.' }
        format.json { render :show, status: :created, location: @bitacora }
      else
        format.html { render :new }
        format.json { render json: @bitacora.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bitacoras/1
  # PATCH/PUT /bitacoras/1.json
  def update
    respond_to do |format|
      if @bitacora.update(bitacora_params)
        format.html { redirect_to @bitacora, notice: 'Bitacora was successfully updated.' }
        format.json { render :show, status: :ok, location: @bitacora }
      else
        format.html { render :edit }
        format.json { render json: @bitacora.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bitacoras/1
  # DELETE /bitacoras/1.json
  def destroy
    @bitacora.destroy
    respond_to do |format|
      format.html { redirect_to bitacoras_url, notice: 'Bitacora was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bitacora
      @bitacora = Bitacora.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bitacora_params
      params.require(:bitacora).permit(:nombre, :telefono, :correo, :municipio, :estado, :area, :acreditado, :alcalde, :esquema, :convenio, :tipo, :acuerdo, :fechaacuerdo, :fechaseguimiento, :fechaevaluacion, :resultado, :tema, :pcfechallamada, :pcfechacorreo, :pcfechaobservaciones, :scfechallamada, :scfechacorreo, :scobservaciones, :estatus, :gruposcomunitarios, :ampliacionmetas, :tcfechallamada, :tcfechacorreo, :tcobservaciones, :estructura)
    end
end

app/helpers/bitacoras_helper.rb
module BitacorasHelper
end

app/views/bitacoras/edit.html.erb
<h1>Editing Bitacora</h1>

<%= render 'form' %>

<%= link_to 'Show', @bitacora %> |
<%= link_to 'Back', bitacoras_path %>

app/views/bitacoras/index.html.erb
<%= search_form_for(@search, :html => {class: "", role: "form"}) do |f| %>

  <div class="container">
   <h4><p id="notice"><%= notice %></p></h4>

  <h2>Buscar Beneficiario</h2>
 <div class="row">
<div class="col-lg-3">
<div class="form-group">
<%= f.label :nombre_cont, "Nombre" %>
<%= f.text_field :nombre_cont, class: "form-control", placeholder: "Nombre", autofocus: true %>
  </div>
</div>
<div class="col-lg-3">
<div class="form-group">
<%= f.label :telefono_cont, "Teléfono" %>
<%= f.text_field :telefono_cont, class: "form-control", placeholder: "Teléfono", autofocus: true %>
  </div>
</div>
<div class="col-lg-3">
<div class="form-group">
<%= f.label :correo_cont, "Email" %>
<%= f.text_field :correo_cont, class: "form-control", placeholder: "Email", autofocus: true %>
  </div>
</div>

</div>
<div class="row">
<div class="col-lg-3">
<div class="form-group">
<%= f.label :municipio_cont, "Municipio" %>
<%= f.text_field :municipio_cont, class: "form-control", placeholder: "Municipio ", autofocus: true %>
  </div>
</div>
<div class="col-lg-3">
<div class="form-group">
<%= f.label :estado_cont, "Estado" %>
    
    <%= f.select :estado_cont, [["Aguascalientes", "Aguascalientes"], ["Baja California", "Baja California"], ["Baja California Sur", "Baja California Sur"], ["Campeche", "Campeche"], ["Chiapas", "Chiapas"], ["Chihuahua", "Chihuahua"], ["Coahuila", "Coahuila"], ["Colima", "Colima"], ["Ciudad de México", "Ciudad de México"], ["Durango", "Durango"], ["Estado de México", "Estado de México"], ["Guanajuato", "Guanajuato"], ["Guerrero", "Guerrero"], ["Hidalgo", "Hidalgo"], ["Jalisco", "Jalisco"], ["Michoacán", "Michoacán"], ["Morelos", "Morelos"], ["Nayarit", "Nayarit"], ["Nuevo León", "Nuevo León"], ["Oaxaca", "Oaxaca"], ["Puebla", "Puebla"], ["Querétaro", "Querétaro"], ["Quintana Roo", "Quintana Roo"], ["San Luis Potosí", "San Luis Potosí"], ["Sinaloa", "Sinaloa"], ["Sonora", "Sonora"], ["Tabasco", "Tabasco"], ["Tamaulipas", "Tamaulipas"], ["Tlaxcala", "Tlaxcala"], ["Veracruz", "Veracruz"], ["Yucatán", "Yucatán"], ["Zacatecas", "Zacatecas"]], {:prompt => "Elegir"}, { class: "form-control" } %>

    
  </div>
</div>
<div class="col-lg-3">
<div class="form-group">
<%= f.label :area_cont, "Area" %>
<%= f.text_field :area_cont, class: "form-control", placeholder: "Area ", autofocus: true %>
  </div>
</div>
</div>
<div class="row">
  <div class="form-group">
  <div class=" col-lg-1">

  <%= f.submit class: 'btn btn-primary btn-lg' %></div>
 
  <div class="col-lg-1">
    <%= f.submit "Reset", :type => "reset", class: 'btn btn-primary btn-lg' %>
  </div>
   </div>
</div>
<% end %>
</div>








<div class="container-fluid">
   <div class="row">
      <div class="col-lg-4 text-left">
        <%= link_to 'Agregar', new_bitacora_path, :class => "btn btn-primary btn_agregar" %>
      </div>
      <div class="col-lg-8 text-right">
        <%= will_paginate @bitacoras, renderer: BootstrapPagination::Rails %> 
     

    </div>
   <div class="col-lg-12  custyle">
    <table class="table table-striped custab">

  <thead>
    <tr><th><%= sort_link(@search, :estatus, "Estatus") %></th>
       <th><%= sort_link(@search, :nombre, "Nombre") %></th>
      <th><%= sort_link(@search, :telefono, "Telefono")%></th>
      <th><%= sort_link(@search, :correo, "Correo")%></th>
      <th><%= sort_link(@search, :estado, "Estado")%></th>
      <th><%= sort_link(@search, :municipio, "Municipio")%></th>
      <th><%= sort_link(@search, :area, "Area")%></th>
        <th><%= sort_link(@search, :alcalde, "Alcalde")%></th>
      <th><%= sort_link(@search, :estructura, "Estructura")%></th>
        <th><%= sort_link(@search, :gruposcomunitarios, "Grupos comunitarios")%></th>
         <th><%= sort_link(@search, :ampliacionmetas, "Ampliación de metas")%></th>
       <th><%= sort_link(@search, :convenio, "Convenio")%></th>
       <th><%= sort_link(@search, :tema, "Temas a convenir")%></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bitacoras.each do |bitacora| %>
      <tr>
      <td><%= bitacora.estatus %></td>
        <td><%= bitacora.nombre %></td>
        <td><%= bitacora.telefono %></td>
        <td><%= bitacora.correo %></td>
        <td><%= bitacora.estado %></td>
        <td><%= bitacora.municipio %></td>
        <td><%= bitacora.area %></td>
        <td><%= bitacora.alcalde %></td>
        <td><%= bitacora.estructura %></td>
        <td><%= bitacora.gruposcomunitarios %></td>
        <td><%= bitacora.ampliacionmetas %></td>
        <td><%= bitacora.convenio %></td>
        <td><%= bitacora.tema %></td>
       
        <td><%= link_to 'Ver', bitacora %></td>
        <td><%= link_to 'Editar', edit_bitacora_path(bitacora) %></td>
        <td><%= link_to 'Eliminar', bitacora, method: :delete, data: { confirm: 'Esta seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>




</div>
 
</div>
</div>

<br>

app/views/bitacoras/new.html.erb
<div class="container">
<div class="row">
<div class="col-md-12">
<h2>Nuevo registro</h2>

<%= render 'form' %>

<%= link_to 'Back', bitacoras_path, class: 'btn btn-primary'  %>
</div>
</div>
</div>

app/views/bitacoras/show.html.erb
<div class="container">
<div class="row">
<div class="col-lg-12">
<h2><b>Beneficiario:</b><%= @bitacora.nombre %></h2>
</div>
<div class="col-lg-12">
<%= link_to 'Editar', edit_bitacora_path(@bitacora), class: 'btn btn-primary' %> 
<%= link_to 'Atras', bitacoras_path, class: 'btn btn-primary'%>
</div>
<div class="col-lg-12  custyle">

    <table class="table table-striped custab">
<thead> 
<tr>
  <th class="thshow">Estatus:</th>
<th class="thshow">Nombre:</th>
<th class="thshow">Teléfono:</th>
<th class="thshow">Email:</th>
<th class="thshow"> Estado</th>
<th class="thshow">Municipio:</th>
<th class="thshow">Area:</th>
<th class="thshow">Alcalde</th>
<th class="thshow">Estructura:</th>

</tr>
</thead>

    <tbody>
   
    <tr>                                     
        
        <td class="tdshow"><%= @bitacora.estatus %></td>        
        <td class="tdshow"><%= @bitacora.nombre %></td>         
        <td class="tdshow"><%= @bitacora.telefono %></td>     
        <td class="tdshow"><%= @bitacora.correo %></td>
        <td class="tdshow"><%= @bitacora.estado %></td>
        <td class="tdshow"> <%= @bitacora.municipio %></td>
        <td class="tdshow"><%= @bitacora.area %></td>
        <td class="tdshow"><%= @bitacora.alcalde  %></td>       
        <td class="tdshow"><%= @bitacora.estructura %></td>
      </tr>
    </tbody>
        </table>

   </div>


</div>

<div class="row">
<div class="col-lg-6">
<h3>Vertiente</h3>
<table class="table table-striped custab">
<thead> 
<tr>
<th class="thshow">Grupos comunitarios</th>
<th class="thshow">Ampliación de metas</th>
</tr>
</thead>
 <tbody>
   
    <tr>
        
        <td class="tdshow"><%= @bitacora.gruposcomunitarios %></td>        
        <td class="tdshow"><%= @bitacora.ampliacionmetas %></td>         
        </tr>
    </tbody>
        </table>
      
   </div>


<div class="col-lg-6">
<h3>Convenio</h3>
<table class="table table-striped custab">
<thead> 
<tr>
<th class="thshow">Convenio</th>
<th class="thshow">Tema</th>
</tr>
</thead>
<tbody>
   <tr>
     <td class="tdshow"><%= @bitacora.convenio %></td>        
      <td class="tdshow"><%= @bitacora.tema %></td>         
        </tr>
           </tbody>
            </table>
      </div>

</div>

<div class="row">
<div class="col-lg-6">
<h3>Primer contacto</h3>
<table class="table table-striped custab">
<thead> 
<tr>
<th class="thshow">Fecha/Llamada:</th>
<th class="thshow">Fecha/correo:</th>
<th class="thshow">Observaciones:</th>
</tr>
</thead>
<tbody>
   <tr>
     <td class="tdshow"><%= @bitacora.pcfechallamada %></td>        
      <td class="tdshow"><%= @bitacora.pcfechacorreo%></td>  
      <td class="tdshow"><%= @bitacora.pcfechaobservaciones%></td>         
        </tr>
           </tbody>
            </table>
              </div>
 
  <div class="col-lg-6">
            <h3>Segundo Contacto contacto</h3>
<table class="table table-striped custab">
<thead> 
<tr>
<th class="thshow">Fecha/Llamada:</th>
<th class="thshow">Fecha/correo:</th>
<th class="thshow">Observaciones:</th>
</tr>
</thead>
<tbody>
   <tr>
     <td class="tdshow"><%= @bitacora.scfechallamada%></td>        
      <td class="tdshow"><%= @bitacora.scfechacorreo%></td>  
      <td class="tdshow"><%= @bitacora.scobservaciones%></td>         
        </tr>
           </tbody>
            </table>
            </div>
 
<div class="col-lg-6">          
            <h3>Tercer Contacto contacto</h3>
<table class="table table-striped custab">
<thead> 
<tr>
<th class="thshow">Fecha/Llamada:</th>
<th class="thshow">Fecha/correo:</th>
<th class="thshow">Observaciones:</th>
</tr>
</thead>
<tbody>
   <tr>
     <td class="tdshow"><%= @bitacora.tcfechallamada%></td>        
      <td class="tdshow"><%= @bitacora.tcfechacorreo%></td>  
      <td class="tdshow"><%= @bitacora.tcobservaciones%></td>         
        </tr>
           </tbody>
            </table>
            </div>
            </div>
            <div class="row">
            <div class="col-lg-8">
            <h3>Resultado</h3>
<table class="table table-striped custab">
<thead> 
<tr>
<th class="thshow">Resultado:</th>

</tr>
</thead>
<tbody>
   <tr>
      <td class="tdshow"><%= @bitacora.resultado%></td>         
        </tr>
           </tbody>
            </table>
            </div>
            </div>



</div>