config/routes.rb
Rails.application.routes.draw do
  resources :bitacoras
  resources :voluntarios
  resources :registros
  resources :registers

   root :to => "bienvenida#index"

end

app/models/registro.rb
class Registro < ActiveRecord::Base
end

app/controllers/registros_controller.rb
class RegistrosController < ApplicationController
  before_action :set_registro, only: [:show, :edit, :update, :destroy]
def index
    @search = Registro.search(params[:q])
    @registros = @search.result
  end 
  # GET /registros
  # GET /registros.json
  def index
    @registros = Registro.all
  end

  # GET /registros/1
  # GET /registros/1.json
  def show
  end

  # GET /registros/new
  def new
    @registro = Registro.new
  end

  # GET /registros/1/edit
  def edit
  end

  # POST /registros
  # POST /registros.json
  def create
    @registro = Registro.new(registro_params)

    respond_to do |format|
      if @registro.save
        format.html { redirect_to @registro, notice: 'Registro was successfully created.' }
        format.json { render :show, status: :created, location: @registro }
      else
        format.html { render :new }
        format.json { render json: @registro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registros/1
  # PATCH/PUT /registros/1.json
  def update
    respond_to do |format|
      if @registro.update(registro_params)
        format.html { redirect_to @registro, notice: 'Registro was successfully updated.' }
        format.json { render :show, status: :ok, location: @registro }
      else
        format.html { render :edit }
        format.json { render json: @registro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registros/1
  # DELETE /registros/1.json
  def destroy
    @registro.destroy
    respond_to do |format|
      format.html { redirect_to registros_url, notice: 'Registro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_registro
      @registro = Registro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def registro_params
      params.require(:registro).permit(:numero, :nombregrupo, :estado, :municipio, :localidad, :colonia, :disponible)
    end
end

app/helpers/registros_helper.rb
module RegistrosHelper
end

app/views/registros/_form.html.erb
<%= form_for(@registro) do |f| %>
  <% if @registro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@registro.errors.count, "error") %> prohibited this registro from being saved:</h2>

      <ul>
      <% @registro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :numero %><br>
    <%= f.number_field :numero %>
  </div>
  <div class="field">
    <%= f.label :nombregrupo %><br>
    <%= f.text_field :nombregrupo %>
  </div>
  <div class="field">
  <% estados = {
      'Oaxaca' => 'Oaxaca', 'Puebla' => 'Puebla'} %>


      
    <%= f.label :estado %><br>
    <%= f.select :estado,estados %>


  </div>
  <div class="field">
    <%= f.label :municipio %><br>
    <%= f.text_field :municipio %>
  </div>
  <div class="field">
    <%= f.label :localidad %><br>
    <%= f.text_field :localidad %>
  </div>
  <div class="field">
    <%= f.label :colonia %><br>
    <%= f.text_field :colonia %>
  </div>
  <div class="field">
    <%= f.label :disponible %><br>
    <%= f.check_box :disponible %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/registros/edit.html.erb
<h1>Editing Registro</h1>

<%= render 'form' %>

<%= link_to 'Show', @registro %> |
<%= link_to 'Back', registros_path %>

app/views/registros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Registros</h1>

<%= search_form_for @search do |f| %>
  <div class="field">
    <%= f.label :nombre, "Name contains" %>
    <%= f.text_field :nombre %>
  </div>
  <div class="actions"><%= f.submit "Search" %></div>
<% end %>

<table>
  <thead>
    <tr>
      <th>Numero</th>
      <th>Nombregrupo</th>
      <th>Estado</th>
      <th>Municipio</th>
      <th>Localidad</th>
      <th>Colonia</th>
      <th>Disponible</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @registros.each do |registro| %>
      <tr>
        <td><%= registro.numero %></td>
        <td><%= registro.nombregrupo %></td>
        <td><%= registro.estado %></td>
        <td><%= registro.municipio %></td>
        <td><%= registro.localidad %></td>
        <td><%= registro.colonia %></td>
        <td><%= registro.disponible %></td>
        <td><%= link_to 'Show', registro %></td>
        <td><%= link_to 'Edit', edit_registro_path(registro) %></td>
        <td><%= link_to 'Destroy', registro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Registro', new_registro_path %>

app/views/registros/new.html.erb
<h1>New Registro</h1>

<%= render 'form' %>

<%= link_to 'Back', registros_path %>

app/views/registros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Numero:</strong>
  <%= @registro.numero %>
</p>

<p>
  <strong>Nombregrupo:</strong>
  <%= @registro.nombregrupo %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @registro.estado %>
</p>

<p>
  <strong>Municipio:</strong>
  <%= @registro.municipio %>
</p>

<p>
  <strong>Localidad:</strong>
  <%= @registro.localidad %>
</p>

<p>
  <strong>Colonia:</strong>
  <%= @registro.colonia %>
</p>

<p>
  <strong>Disponible:</strong>
  <%= @registro.disponible %>
</p>

<%= link_to 'Edit', edit_registro_path(@registro) %> |
<%= link_to 'Back', registros_path %>